RDKCOM-3648: RDKBDEV-1470: reduce usage of legacy vsystem() API
Reason for change:
reduce usage of legacy vsystem() API
Code cleanup
This fixes the RPi and Turris build error:
| CcspPandM/source/TR-181/middle_layer_src/cosa_dslite_dml.c:107:14: error: call to 'format_error' declared with attribute error: command argument cannot be a variable
| replace "sprintf(buffer, command, args); v_secure_system(buffer);" with "v_secure_system(command, args);"
|   107 |         rc = v_secure_system(UPDATE_RESOLV_CMD);
|       |
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Simon Chung <simon.chung@rdkcentral.com>

(cherry picked from commit 99f5b55109e3ef8744e0f95d5f6cb20f176c117a)
Change-Id: I9f0586b911c85d206d0897bb08c09f4e18e7f0dd